version: '3'

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - rabbit
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - "5673:5672"
  celery:
    restart: always
    build:
      context: .
    command: celery -A app.celery worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - app
      - rabbit
