# Generated by Django 3.2 on 2021-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='id',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video_id',
            field=models.CharField(default='', max_length=256, primary_key=True, serialize=False),
        ),
    ]
