# Generated by Django 3.2 on 2021-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_youtubevideo_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPIKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('last_expired', models.DateTimeField(default=None)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_index', models.IntegerField(default=-1)),
            ],
        ),
    ]
