# Generated by Django 3.2 on 2021-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_googleapikeys_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapikeys',
            name='last_expired',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='key_index',
            field=models.IntegerField(default=1),
        ),
    ]
