# Generated by Django 3.2 on 2021-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210420_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapikeys',
            name='last_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
